### ISSUE TITLE
Approx Date For Next Release?

### ISSUE THREAD

**Issue by Wafiismail27** [OpenBuilders/notcoin-clicker#4]
- turbo mode (rockets)
- no-API logic (anti-fraud)
- morse clicker

Any ETA on when you guys may release this?

**Comment by chakzefir** [comment]
No plans.

**Comment by l3lack-l3erry** [comment]
How do I launch a clicker?

**Comment by l3lack-l3erry** [comment]
Which file should I put on launch

**Comment by chakzefir** [comment]
> How do I launch a clicker?

Please refer to to [readme](https://github.com/OpenBuilders/notcoin-clicker?tab=readme-ov-file#how-to-run)
